# Generated by Django 4.0.3 on 2022-04-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyForToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabinet_five', models.CharField(max_length=250)),
                ('kabinet_four', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Дежурные',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_end', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
                ('image_field', models.ImageField(upload_to='')),
                ('ssilka', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Плитка',
            },
        ),
        migrations.CreateModel(
            name='NumbersPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name_plural': 'Номера телефонов',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('technics_type', models.ManyToManyField(to='home.numbersphone')),
            ],
            options={
                'verbose_name_plural': 'Ответственные за ППО',
            },
        ),
    ]
